import { WordBook } from '@/types/wordbookTypes'

export const chapterList = [
  [
    '1. 인사',
    '2. 날짜',
    '3. 시간',
    '4. 날씨',
    '5. 가족',
    '6. 학교',
    '7. 음식',
    '8. 색깔',
    '9. 교통',
    '10. 숫자',
  ],
  [
    '1. 직업',
    '2. 공부',
    '3. 여행',
    '4. 친구',
    '5. 음료',
    '6. 계절',
    '7. 생활',
    '8. 길 찾기',
    '9. 쇼핑',
    '10. 건강',
  ],
  [
    '1. 취미',
    '2. 환경',
    '3. 운동',
    '4. 문화',
    '5. 요리',
    '6. 기술',
    '7. 사회',
    '8. 정치',
    '9. 경제',
    '10. 상업',
  ],
  [
    '1. 예술',
    '2. 과학',
    '3. 철학',
    '4. 언어',
    '5. 문학',
    '6. 미디어',
    '7. 커뮤니케이션',
    '8. 혁신',
    '9. 직장',
    '10. 학습',
  ],
  [
    '1. 사회',
    '2. 정치',
    '3. 경제',
    '4. 상업',
    '5. 과학',
    '6. 기술',
    '7. 문화',
    '8. 역사',
    '9. 교육',
    '10. 환경',
  ],
  [
    '1. 철학',
    '2. 윤리',
    '3. 언어',
    '4. 문학',
    '5. 국제 문제',
    '6. 기술',
    '7. 혁신',
    '8. 일상 생활',
    '9. 사회',
    '10. 미디어',
  ],
]

const hsk1_chapters = [
  {
    wordBookId: 0,
    chapterId: 0,
    chapter: '1. 인사',
    chapterDescription: '인사에 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 1,
    chapter: '2. 날짜',
    chapterDescription: '날짜와 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 2,
    chapter: '3. 시간',
    chapterDescription: '시간에 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 3,
    chapter: '4. 날씨',
    chapterDescription: '날씨와 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 4,
    chapter: '5. 가족',
    chapterDescription: '가족과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 5,
    chapter: '6. 학교',
    chapterDescription: '학교와 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 6,
    chapter: '7. 음식',
    chapterDescription: '음식과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 7,
    chapter: '8. 색깔',
    chapterDescription: '색깔과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 8,
    chapter: '9. 교통',
    chapterDescription: '교통과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 0,
    chapterId: 9,
    chapter: '10. 숫자',
    chapterDescription: '숫자와 관련된 단어들입니다.',
    chapterLength: 10,
  },
]
const hsk2_chapters = [
  {
    wordBookId: 1,
    chapterId: 0,
    chapter: '1. 직업',
    chapterDescription: '직업에 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 1,
    chapter: '2. 공부',
    chapterDescription: '공부와 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 2,
    chapter: '3. 여행',
    chapterDescription: '여행과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 3,
    chapter: '4. 친구',
    chapterDescription: '친구와 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 4,
    chapter: '5. 음료',
    chapterDescription: '음료와 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 5,
    chapter: '6. 계절',
    chapterDescription: '계절과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 6,
    chapter: '7. 생활',
    chapterDescription: '생활과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 7,
    chapter: '8. 길 찾기',
    chapterDescription: '길 찾기에 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 8,
    chapter: '9. 쇼핑',
    chapterDescription: '쇼핑과 관련된 단어들입니다.',
    chapterLength: 10,
  },
  {
    wordBookId: 1,
    chapterId: 9,
    chapter: '10. 건강',
    chapterDescription: '건강에 관련된 단어들입니다.',
    chapterLength: 10,
  },
]
const hsk3_chapters = [
  {
    wordBookId: 2,
    chapterId: 0,
    chapter: '1. 취미',
    chapterDescription: '취미에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 1,
    chapter: '2. 환경',
    chapterDescription: '환경에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 2,
    chapter: '3. 운동',
    chapterDescription: '운동에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 3,
    chapter: '4. 문화',
    chapterDescription: '문화에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 4,
    chapter: '5. 요리',
    chapterDescription: '요리에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 5,
    chapter: '6. 기술',
    chapterDescription: '기술에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 6,
    chapter: '7. 사회',
    chapterDescription: '사회에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 7,
    chapter: '8. 정치',
    chapterDescription: '정치에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 8,
    chapter: '9. 경제',
    chapterDescription: '경제에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 2,
    chapterId: 9,
    chapter: '10. 상업',
    chapterDescription: '상업에 관련된 단어들입니다.',
    chapterLength: 20,
  },
]
const hsk4_chapters = [
  {
    wordBookId: 3,
    chapterId: 0,
    chapter: '1. 예술',
    chapterDescription: '예술에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 1,
    chapter: '2. 과학',
    chapterDescription: '과학에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 2,
    chapter: '3. 철학',
    chapterDescription: '철학에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 3,
    chapter: '4. 언어',
    chapterDescription: '언어에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 4,
    chapter: '5. 문학',
    chapterDescription: '문학에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 5,
    chapter: '6. 미디어',
    chapterDescription: '미디어에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 6,
    chapter: '7. 커뮤니케이션',
    chapterDescription: '커뮤니케이션에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 7,
    chapter: '8. 혁신',
    chapterDescription: '혁신에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 8,
    chapter: '9. 직장',
    chapterDescription: '직장에 관련된 단어들입니다.',
    chapterLength: 20,
  },
  {
    wordBookId: 3,
    chapterId: 9,
    chapter: '10. 학습',
    chapterDescription: '학습에 관련된 단어들입니다.',
    chapterLength: 20,
  },
]
const hsk5_chapters = [
  {
    wordBookId: 4,
    chapterId: 0,
    chapter: '1. 사회',
    chapterDescription: '사회에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 1,
    chapter: '2. 정치',
    chapterDescription: '정치에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 2,
    chapter: '3. 경제',
    chapterDescription: '경제에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 3,
    chapter: '4. 상업',
    chapterDescription: '상업에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 4,
    chapter: '5. 과학',
    chapterDescription: '과학에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 5,
    chapter: '6. 기술',
    chapterDescription: '기술에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 6,
    chapter: '7. 문화',
    chapterDescription: '문화에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 7,
    chapter: '8. 역사',
    chapterDescription: '역사에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 8,
    chapter: '9. 교육',
    chapterDescription: '교육에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 4,
    chapterId: 9,
    chapter: '10. 환경',
    chapterDescription: '환경에 관련된 단어들입니다.',
    chapterLength: 30,
  },
]
const hsk6_chapters = [
  {
    wordBookId: 5,
    chapterId: 0,
    chapter: '1. 철학',
    chapterDescription: '철학에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 1,
    chapter: '2. 윤리',
    chapterDescription: '윤리에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 2,
    chapter: '3. 언어',
    chapterDescription: '언어에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 3,
    chapter: '4. 문학',
    chapterDescription: '문학에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 4,
    chapter: '5. 국제 문제',
    chapterDescription: '국제 문제에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 5,
    chapter: '6. 기술',
    chapterDescription: '기술에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 6,
    chapter: '7. 혁신',
    chapterDescription: '혁신에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 7,
    chapter: '8. 일상 생활',
    chapterDescription: '일상 생활에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 8,
    chapter: '9. 사회',
    chapterDescription: '사회에 관련된 단어들입니다.',
    chapterLength: 30,
  },
  {
    wordBookId: 5,
    chapterId: 9,
    chapter: '10. 미디어',
    chapterDescription: '미디어에 관련된 단어들입니다.',
    chapterLength: 30,
  },
]

export const wordBooks: WordBook[] = [
  {
    wordBookId: 0,
    wordBookTitle: 'hsk 1급 단어장',
    wordBookDescription: '초급 단어장입니다.',
    wordBookLength: 100,
    chapterList: hsk1_chapters,
  },
  {
    wordBookId: 1,
    wordBookTitle: 'hsk 2급 단어장',
    wordBookDescription: '중급 단어장입니다.',
    wordBookLength: 100,
    chapterList: hsk2_chapters,
  },
  {
    wordBookId: 2,
    wordBookTitle: 'hsk 3급 단어장',
    wordBookDescription: '고급 단어장입니다.',
    wordBookLength: 100,
    chapterList: hsk3_chapters,
  },
  {
    wordBookId: 3,
    wordBookTitle: 'hsk 4급 단어장',
    wordBookDescription: '최고급 단어장입니다.',
    wordBookLength: 100,
    chapterList: hsk4_chapters,
  },
  {
    wordBookId: 4,
    wordBookTitle: 'hsk 5급 단어장',
    wordBookDescription: '최고급 단어장입니다.',
    wordBookLength: 100,
    chapterList: hsk5_chapters,
  },
  {
    wordBookId: 5,
    wordBookTitle: 'hsk 6급 단어장',
    wordBookDescription: '최고급 단어장입니다.',
    wordBookLength: 100,
    chapterList: hsk6_chapters,
  },
]
